### ISSUE TITLE
WHAT ARE STEPS TO INSTALL YOUR BOT CODES ?

### ISSUE THREAD

**Issue by YUVRAJABNISH** [trizin/Telegram-Airdrop-Bot#15]

**Comment by trizin** [comment]
You can set up the bot by following the instructions here: https://github.com/trizin/Telegram-Airdrop-Bot#installation-with-docker

**Comment by YUVRAJABNISH** [comment]
Any app to run script

**Comment by trizin** [comment]
> Any app to run script

Only [Docker](https://www.docker.com/) is required.
