### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by fede-schwindt** [trizin/Telegram-Airdrop-Bot#2]
When I try to run the command `docker-compose up -d` the console gives me an error, I checked the .env file and everything is fine. I'm a beginner so a little help wouldn't hurt.
![Captura](https://user-images.githubusercontent.com/86686019/124181644-2d95ca00-da8c-11eb-967f-09be695d403d.PNG)

**Comment by trizin** [comment]
It seems like docker-compose is not able to connect to docker socket. Are you sure your docker is running?

**Comment by fede-schwindt** [comment]
I will check it and in case it is not running I will investigate how to do it, thanks for answering. 😃

**Comment by fede-schwindt** [comment]
> It seems like docker-compose is not able to connect to docker socket. Are you sure your docker is running?

I will check it and in case it is not running I will investigate how to do it, thanks for answering. 😃

**Comment by trizin** [comment]
Reopen the issue if you need further help!
